//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.09 at 10:45:26 AM EST 
//


package org.jentrata.ebxml.cpa;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for actor.type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="actor.type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="urn:oasis:names:tc:ebxml-msg:actor:nextMSH"/>
 *     &lt;enumeration value="urn:oasis:names:tc:ebxml-msg:actor:toPartyMSH"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "actor.type")
@XmlEnum
public enum ActorType {

    @XmlEnumValue("urn:oasis:names:tc:ebxml-msg:actor:nextMSH")
    URN_OASIS_NAMES_TC_EBXML_MSG_ACTOR_NEXT_MSH("urn:oasis:names:tc:ebxml-msg:actor:nextMSH"),
    @XmlEnumValue("urn:oasis:names:tc:ebxml-msg:actor:toPartyMSH")
    URN_OASIS_NAMES_TC_EBXML_MSG_ACTOR_TO_PARTY_MSH("urn:oasis:names:tc:ebxml-msg:actor:toPartyMSH");
    private final String value;

    ActorType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ActorType fromValue(String v) {
        for (ActorType c: ActorType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
