//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.09 at 10:45:26 AM EST 
//


package org.jentrata.ebxml.cpa;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ThisPartyActionBinding" type="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}ActionBinding.type"/>
 *         &lt;element name="OtherPartyActionBinding" type="{http://www.w3.org/2001/XMLSchema}IDREF" minOccurs="0"/>
 *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}CanReceive" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "thisPartyActionBinding",
    "otherPartyActionBinding",
    "canReceive"
})
@XmlRootElement(name = "CanSend")
public class CanSend {

    @XmlElement(name = "ThisPartyActionBinding", required = true)
    protected ActionBindingType thisPartyActionBinding;
    @XmlElement(name = "OtherPartyActionBinding")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object otherPartyActionBinding;
    @XmlElement(name = "CanReceive")
    protected List<CanReceive> canReceive;

    /**
     * Gets the value of the thisPartyActionBinding property.
     * 
     * @return
     *     possible object is
     *     {@link ActionBindingType }
     *     
     */
    public ActionBindingType getThisPartyActionBinding() {
        return thisPartyActionBinding;
    }

    /**
     * Sets the value of the thisPartyActionBinding property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionBindingType }
     *     
     */
    public void setThisPartyActionBinding(ActionBindingType value) {
        this.thisPartyActionBinding = value;
    }

    /**
     * Gets the value of the otherPartyActionBinding property.
     * 
     * @return
     *     possible object is
     *     {@link ActionBindingType }
     *     
     */
    public ActionBindingType getOtherPartyActionBinding() {
        return (ActionBindingType) otherPartyActionBinding;
    }

    /**
     * Sets the value of the otherPartyActionBinding property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setOtherPartyActionBinding(Object value) {
        this.otherPartyActionBinding = value;
    }

    /**
     * Gets the value of the canReceive property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the canReceive property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCanReceive().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CanReceive }
     * 
     * 
     */
    public List<CanReceive> getCanReceive() {
        if (canReceive == null) {
            canReceive = new ArrayList<CanReceive>();
        }
        return this.canReceive;
    }

}
