//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.09 at 10:45:26 AM EST 
//


package org.jentrata.ebxml.cpa;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}ebXMLSenderBinding" minOccurs="0"/>
 *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}ebXMLReceiverBinding" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="docExchangeId" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ebXMLSenderBinding",
    "ebXMLReceiverBinding"
})
@XmlRootElement(name = "DocExchange")
public class DocExchange {

    protected EbXMLSenderBinding ebXMLSenderBinding;
    protected EbXMLReceiverBinding ebXMLReceiverBinding;
    @XmlAttribute(name = "docExchangeId", namespace = "http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String docExchangeId;

    /**
     * Gets the value of the ebXMLSenderBinding property.
     * 
     * @return
     *     possible object is
     *     {@link EbXMLSenderBinding }
     *     
     */
    public EbXMLSenderBinding getEbXMLSenderBinding() {
        return ebXMLSenderBinding;
    }

    /**
     * Sets the value of the ebXMLSenderBinding property.
     * 
     * @param value
     *     allowed object is
     *     {@link EbXMLSenderBinding }
     *     
     */
    public void setEbXMLSenderBinding(EbXMLSenderBinding value) {
        this.ebXMLSenderBinding = value;
    }

    /**
     * Gets the value of the ebXMLReceiverBinding property.
     * 
     * @return
     *     possible object is
     *     {@link EbXMLReceiverBinding }
     *     
     */
    public EbXMLReceiverBinding getEbXMLReceiverBinding() {
        return ebXMLReceiverBinding;
    }

    /**
     * Sets the value of the ebXMLReceiverBinding property.
     * 
     * @param value
     *     allowed object is
     *     {@link EbXMLReceiverBinding }
     *     
     */
    public void setEbXMLReceiverBinding(EbXMLReceiverBinding value) {
        this.ebXMLReceiverBinding = value;
    }

    /**
     * Gets the value of the docExchangeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocExchangeId() {
        return docExchangeId;
    }

    /**
     * Sets the value of the docExchangeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocExchangeId(String value) {
        this.docExchangeId = value;
    }

}
