//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.09 at 10:45:26 AM EST 
//


package org.jentrata.ebxml.cpa;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for persistenceLevel.type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="persistenceLevel.type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}Name">
 *     &lt;enumeration value="none"/>
 *     &lt;enumeration value="transient"/>
 *     &lt;enumeration value="persistent"/>
 *     &lt;enumeration value="transient-and-persistent"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "persistenceLevel.type")
@XmlEnum
public enum PersistenceLevelType {

    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("transient")
    TRANSIENT("transient"),
    @XmlEnumValue("persistent")
    PERSISTENT("persistent"),
    @XmlEnumValue("transient-and-persistent")
    TRANSIENT_AND_PERSISTENT("transient-and-persistent");
    private final String value;

    PersistenceLevelType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PersistenceLevelType fromValue(String v) {
        for (PersistenceLevelType c: PersistenceLevelType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
