//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.09 at 10:45:26 AM EST 
//


package org.jentrata.ebxml.cpa;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Retries" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="RetryInterval" type="{http://www.w3.org/2001/XMLSchema}duration" minOccurs="0"/>
 *         &lt;element name="MessageOrderSemantics" type="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}messageOrderSemantics.type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "retries",
    "retryInterval",
    "messageOrderSemantics"
})
@XmlRootElement(name = "ReliableMessaging")
public class ReliableMessaging {

    @XmlElement(name = "Retries")
    protected BigInteger retries;
    @XmlElement(name = "RetryInterval")
    protected Duration retryInterval;
    @XmlElement(name = "MessageOrderSemantics", required = true)
    protected MessageOrderSemanticsType messageOrderSemantics;

    /**
     * Gets the value of the retries property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRetries() {
        return retries;
    }

    /**
     * Sets the value of the retries property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRetries(BigInteger value) {
        this.retries = value;
    }

    /**
     * Gets the value of the retryInterval property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getRetryInterval() {
        return retryInterval;
    }

    /**
     * Sets the value of the retryInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setRetryInterval(Duration value) {
        this.retryInterval = value;
    }

    /**
     * Gets the value of the messageOrderSemantics property.
     * 
     * @return
     *     possible object is
     *     {@link MessageOrderSemanticsType }
     *     
     */
    public MessageOrderSemanticsType getMessageOrderSemantics() {
        return messageOrderSemantics;
    }

    /**
     * Sets the value of the messageOrderSemantics property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageOrderSemanticsType }
     *     
     */
    public void setMessageOrderSemantics(MessageOrderSemanticsType value) {
        this.messageOrderSemantics = value;
    }

}
