//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.09 at 10:45:26 AM EST 
//


package org.jentrata.ebxml.cpa;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DigitalEnvelopeProtocol" type="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}protocol.type"/>
 *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}EncryptionAlgorithm" maxOccurs="unbounded"/>
 *         &lt;element name="EncryptionSecurityDetailsRef" type="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}SecurityDetailsRef.type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "digitalEnvelopeProtocol",
    "encryptionAlgorithm",
    "encryptionSecurityDetailsRef"
})
@XmlRootElement(name = "SenderDigitalEnvelope")
public class SenderDigitalEnvelope {

    @XmlElement(name = "DigitalEnvelopeProtocol", required = true)
    protected ProtocolType digitalEnvelopeProtocol;
    @XmlElement(name = "EncryptionAlgorithm", required = true)
    protected List<EncryptionAlgorithm> encryptionAlgorithm;
    @XmlElement(name = "EncryptionSecurityDetailsRef")
    protected SecurityDetailsRefType encryptionSecurityDetailsRef;

    /**
     * Gets the value of the digitalEnvelopeProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link ProtocolType }
     *     
     */
    public ProtocolType getDigitalEnvelopeProtocol() {
        return digitalEnvelopeProtocol;
    }

    /**
     * Sets the value of the digitalEnvelopeProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProtocolType }
     *     
     */
    public void setDigitalEnvelopeProtocol(ProtocolType value) {
        this.digitalEnvelopeProtocol = value;
    }

    /**
     * Gets the value of the encryptionAlgorithm property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the encryptionAlgorithm property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEncryptionAlgorithm().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EncryptionAlgorithm }
     * 
     * 
     */
    public List<EncryptionAlgorithm> getEncryptionAlgorithm() {
        if (encryptionAlgorithm == null) {
            encryptionAlgorithm = new ArrayList<EncryptionAlgorithm>();
        }
        return this.encryptionAlgorithm;
    }

    /**
     * Gets the value of the encryptionSecurityDetailsRef property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityDetailsRefType }
     *     
     */
    public SecurityDetailsRefType getEncryptionSecurityDetailsRef() {
        return encryptionSecurityDetailsRef;
    }

    /**
     * Sets the value of the encryptionSecurityDetailsRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityDetailsRefType }
     *     
     */
    public void setEncryptionSecurityDetailsRef(SecurityDetailsRefType value) {
        this.encryptionSecurityDetailsRef = value;
    }

}
