//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.09 at 10:45:26 AM EST 
//


package org.jentrata.ebxml.cpa;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for statusValue.type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="statusValue.type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="agreed"/>
 *     &lt;enumeration value="signed"/>
 *     &lt;enumeration value="proposed"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "statusValue.type")
@XmlEnum
public enum StatusValueType {

    @XmlEnumValue("agreed")
    AGREED("agreed"),
    @XmlEnumValue("signed")
    SIGNED("signed"),
    @XmlEnumValue("proposed")
    PROPOSED("proposed");
    private final String value;

    StatusValueType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StatusValueType fromValue(String v) {
        for (StatusValueType c: StatusValueType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
