//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.09 at 10:45:26 AM EST 
//


package org.jentrata.ebxml.cpa;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for syncReplyMode.type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="syncReplyMode.type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="mshSignalsOnly"/>
 *     &lt;enumeration value="responseOnly"/>
 *     &lt;enumeration value="signalsAndResponse"/>
 *     &lt;enumeration value="signalsOnly"/>
 *     &lt;enumeration value="none"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "syncReplyMode.type")
@XmlEnum
public enum SyncReplyModeType {

    @XmlEnumValue("mshSignalsOnly")
    MSH_SIGNALS_ONLY("mshSignalsOnly"),
    @XmlEnumValue("responseOnly")
    RESPONSE_ONLY("responseOnly"),
    @XmlEnumValue("signalsAndResponse")
    SIGNALS_AND_RESPONSE("signalsAndResponse"),
    @XmlEnumValue("signalsOnly")
    SIGNALS_ONLY("signalsOnly"),
    @XmlEnumValue("none")
    NONE("none");
    private final String value;

    SyncReplyModeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SyncReplyModeType fromValue(String v) {
        for (SyncReplyModeType c: SyncReplyModeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
