//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.09 at 10:45:26 AM EST 
//


package org.jentrata.ebxml.cpa;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TransportProtocol" type="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}protocol.type"/>
 *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}AccessAuthentication" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}TransportClientSecurity" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transportProtocol",
    "accessAuthentication",
    "transportClientSecurity"
})
@XmlRootElement(name = "TransportSender")
public class TransportSender {

    @XmlElement(name = "TransportProtocol", required = true)
    protected ProtocolType transportProtocol;
    @XmlElement(name = "AccessAuthentication")
    protected List<AccessAuthenticationType> accessAuthentication;
    @XmlElement(name = "TransportClientSecurity")
    protected TransportClientSecurity transportClientSecurity;

    /**
     * Gets the value of the transportProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link ProtocolType }
     *     
     */
    public ProtocolType getTransportProtocol() {
        return transportProtocol;
    }

    /**
     * Sets the value of the transportProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProtocolType }
     *     
     */
    public void setTransportProtocol(ProtocolType value) {
        this.transportProtocol = value;
    }

    /**
     * Gets the value of the accessAuthentication property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accessAuthentication property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccessAuthentication().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccessAuthenticationType }
     * 
     * 
     */
    public List<AccessAuthenticationType> getAccessAuthentication() {
        if (accessAuthentication == null) {
            accessAuthentication = new ArrayList<AccessAuthenticationType>();
        }
        return this.accessAuthentication;
    }

    /**
     * Gets the value of the transportClientSecurity property.
     * 
     * @return
     *     possible object is
     *     {@link TransportClientSecurity }
     *     
     */
    public TransportClientSecurity getTransportClientSecurity() {
        return transportClientSecurity;
    }

    /**
     * Sets the value of the transportClientSecurity property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransportClientSecurity }
     *     
     */
    public void setTransportClientSecurity(TransportClientSecurity value) {
        this.transportClientSecurity = value;
    }

}
